[workspace]
channels = ["conda-forge"]
name = "cms-integration-challenge"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
awkward = ">=2.8.9"
cabinetry = ">=0.6.0,<0.7"
cloudpickle = ">=3.1.1,<4"
coffea = ">=2025.10.2,<2026"
correctionlib = ">=2.7.0,<3"
dask-awkward = ">=2025.5.0,<2026"
hist = ">=2.8.1,<3"
mplhep = ">=0.4.0,<0.5"
numba = ">=0.61.2,<0.62"
numpy = ">=2.2.6,<3"
omegaconf = ">=2.3.0,<3"
pandas = ">=2.3.1,<3"
pydantic = ">=2.11.7,<3"
scikit-learn = ">=1.7.1,<2"
scipy = ">=1.16.0,<2"
tabulate = ">=0.9.0,<0.10"
tqdm = ">=4.67.1,<5"
vector = "==1.5.1" # ">=1.6.3,<2"
python = ">=3.12.11,<3.13"
xrootd = ">=5.8.1,<6"
ipython = ">=9.4.0,<10"
fsspec-xrootd = ">=0.4.0"
rich = ">=14.1.0,<15"
ipykernel = ">=6.30.1,<7"
ipywidgets = ">=8.1.7,<9"
nbstripout = ">=0.8.1,<0.9"

[feature.dev.dependencies]
scikit-hep-testdata = ">=0.4.0"
pytest = ">=8.0.0"
pytest-cov = ">=4.0.0"

[feature.dev.pypi-dependencies]
rucio = ">=37.7.1, <38"

[feature.lab.dependencies]
notebook = ">=7.5.0,<8"
jupyterlab = ">=4.5.0,<5"

[feature.lab.tasks.lab]
description = "Start a JupyterLab instance"
cmd = "jupyter lab"

[feature.lab.tasks.start]
description = "Get started with the repository"
depends-on = ["lab"]

[environments]
lab = ["lab"]
dev = ["dev"]

[pypi-dependencies]
rucio = ">=37.7.1, <38"
intccms = { path = ".", editable = true }
