[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "intccms"
version = "2.0.0"
description = "Integration Challenge CMS Analysis Package"
requires-python = ">=3.12"

[tool.hatch.build.targets.wheel]
packages = ["src/intccms"]
