[workspace]
name = "atlas-integration-challenge"
version = "0.0.1"
description = "IRIS-HEP ATLAS integration challenge"
authors = ["Alexander Held <alexander.held@cern.ch>"]
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64"]

[tasks.lab]
description = "Start a JupyterLab instance"
cmd = "jupyter lab"

[tasks.start]
description = "Get started with the repository"
depends-on = ["lab"]

[dependencies]
notebook = ">=7.5.0,<8"
jupyterlab = ">=4.5.0,<5"
mplhep = ">=0.4.1,<0.5"
xrootd = ">=5.8.4,<6"
fsspec-xrootd = ">=0.5.1,<0.6"
ipywidgets = ">=8.1.7,<9"
coffea = ">=2025.10.1,<2026"
atlas-schema = ">=0.4.1,<0.5"
atlasopenmagic = ">=1.6.1,<2"
